# Generated by Django 4.2 on 2023-04-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite',
            field=models.BooleanField(),
        ),
    ]
