# Generated by Django 4.2 on 2023-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
