# Generated by Django 4.2 on 2023-04-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0002_remove_skiresort_favorite'),
        ('favorites', '0003_alter_favorites_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='favorite',
        ),
        migrations.AddField(
            model_name='favorites',
            name='ski_resort',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ski_resorts.skiresort'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
