# Generated by Django 4.2 on 2023-04-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0002_remove_skiresort_favorite'),
        ('favorites', '0004_remove_favorites_favorite_favorites_ski_resort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='ski_resort',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ski_resorts.skiresort'),
        ),
    ]
