# Generated by Django 4.2 on 2023-04-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_alter_favorites_ski_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
