# Generated by Django 4.2 on 2023-04-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiResort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.favorites')),
            ],
        ),
    ]
