# Generated by Django 4.2 on 2023-04-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiresort',
            name='favorite',
        ),
    ]
